### ISSUE TITLE
 Cannot read configuration file web.config

### ISSUE THREAD

**Issue by osudude** [OdeToCode/explore-aspnetcore#2]
@OdeToCode, When I try to run the OdeToFood web app (http://localhost:51791/) from Visual Studio, I get the following error detail:

HTTP Error 500.19 - Internal Server ErrorThe requested page cannot be accessed because the related configuration data for the page is invalid.Error Code   0x80070003Config Error   Cannot read configuration fileConfig File   \?\C:\dev\github\aspnet5samples\OdeToFood\src\OdeToFood\web.config

Do I need to configure something for it to run on my local box?   

Visual Studio 2015 Update 3
Windows 10 Anniversary Edition

From Add/Remove Programs:
Microsoft .NET Core 1.0.0 - SDK Preview 2 (x64)
Microsoft .NET Core 1.0.1 -  SDK 1.0.0 Preview 2-003131 (x64)
Microsoft .NET Core 1.0.1 - VS 2015 Tooling Preview 2

Thanks for the great plural sight course!

**Comment by osudude** [comment]
Think I may have found a fix for this issue.  I made an empty asp.net core project.  Copied the project.json from that.  This caused new errors because of missing dependencies.  Fixed the missing dependency errors.  Also had to swap out launchSettings.json for some reason.  I am guessing there are project.json breaking changes from asp.net core 1.0 to asp.net core 1.0.1?

@OdeToCode can you please point me to where the sql script is for building the OdeToFood database (doesn't seem to auto build the database for some reason)?

thanks!

**Comment by OdeToCode** [comment]
You can generate a script from migrations using `dotnet ef migrations script` at the command line. Or, you can auto run the database create with the code you provided. I'm about to check-in a small update to move that logic into program.cs.
